---
# This playbook updates JAMF Software's Casper Server in Clustered Environments

- hosts: prod
  remote_user: root
  sudo: yes
  serial: 4
  
  roles:
    - stop_services

- hosts: prod_master
  remote_user: root
  sudo: yes
  serial: 1

  roles:
    - webapp

- hosts: prod_nonmaster
  remote_user: root
  sudo: yes
  serial: 2

  roles:
    - webapp